// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2fhGSsrRUXeWdT6wtNPYMtbeGQ-Xyhk',
    appId: '1:496990230712:web:bbcb236c7af99f9064fc4d',
    messagingSenderId: '496990230712',
    projectId: 'capstone-project-92fdf',
    authDomain: 'capstone-project-92fdf.firebaseapp.com',
    databaseURL: 'https://capstone-project-92fdf-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-project-92fdf.appspot.com',
    measurementId: 'G-K3MP7PH4FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8KiKGTMM_jKZHWMtBawgUv7cT5MC1c8',
    appId: '1:496990230712:android:1e44c3b15160a4ef64fc4d',
    messagingSenderId: '496990230712',
    projectId: 'capstone-project-92fdf',
    databaseURL: 'https://capstone-project-92fdf-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-project-92fdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsEO1Ww6He9R_UjUzKYShYdBYmi85qBo',
    appId: '1:496990230712:ios:8126fabe8eec718e64fc4d',
    messagingSenderId: '496990230712',
    projectId: 'capstone-project-92fdf',
    databaseURL: 'https://capstone-project-92fdf-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-project-92fdf.appspot.com',
    iosBundleId: 'com.example.audiovision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQsEO1Ww6He9R_UjUzKYShYdBYmi85qBo',
    appId: '1:496990230712:ios:8126fabe8eec718e64fc4d',
    messagingSenderId: '496990230712',
    projectId: 'capstone-project-92fdf',
    databaseURL: 'https://capstone-project-92fdf-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-project-92fdf.appspot.com',
    iosBundleId: 'com.example.audiovision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi2fhGSsrRUXeWdT6wtNPYMtbeGQ-Xyhk',
    appId: '1:496990230712:web:6f6f1f67c1a4ad3b64fc4d',
    messagingSenderId: '496990230712',
    projectId: 'capstone-project-92fdf',
    authDomain: 'capstone-project-92fdf.firebaseapp.com',
    databaseURL: 'https://capstone-project-92fdf-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-project-92fdf.appspot.com',
    measurementId: 'G-1R1SJ9PC3R',
  );
}
